// First-login-only tracking (login_logs_choices) — one row per user, ever.
// user_id here is the real Eaze platform user id, distinct from phone_number
// (both tracked separately, per the actual identity model) — resolved via
// the host app's banner entry, not generated by this app.
import { dbEnabled, query } from '../db/client.js';
import { istNowParts } from '../lib/ist-time.js';

// ON CONFLICT DO NOTHING against the unique user_id constraint — idempotent,
// safe to call on every login (only the very first call for a given user_id
// ever actually inserts a row).
export async function recordFirstLogin({ userId, phoneNumber }) {
  if (!dbEnabled) return { persisted: false };
  const { date, time } = istNowParts();
  const { rows } = await query(
    `INSERT INTO login_logs_choices (user_id, phone_number, first_login_date, first_login_time)
     VALUES ($1, $2, $3, $4)
     ON CONFLICT (user_id) DO NOTHING
     RETURNING id, user_id, phone_number, first_login_date, first_login_time`,
    [userId, phoneNumber, date, time],
  );
  return { persisted: true, recorded: rows.length > 0, log: rows[0] || null };
}
