# First-login-only tracking (login_logs_choices) — one row per user, ever.
# user_id here is the real Eaze platform user id, resolved via the host
# app's banner entry, not generated by this app. Phone numbers are not
# collected or stored anywhere in this app.
from ..db.client import DB_ENABLED, query
from ..lib.ist_time import ist_now_parts


# ON CONFLICT DO NOTHING against the unique user_id constraint — idempotent,
# safe to call on every login (only the very first call for a given user_id
# ever actually inserts a row).
async def record_first_login(*, user_id):
    if not DB_ENABLED:
        return {"persisted": False}
    parts = ist_now_parts()
    result = await query(
        """INSERT INTO login_logs_choices (user_id, first_login_date, first_login_time)
           VALUES (%s, %s, %s)
           ON CONFLICT (user_id) DO NOTHING
           RETURNING id, user_id, first_login_date, first_login_time""",
        [user_id, parts["date"], parts["time"]],
    )
    rows = result["rows"]
    return {"persisted": True, "recorded": len(rows) > 0, "log": rows[0] if rows else None}
